config/routes.rb
Codebrahma::Application.routes.draw do
  resources :feeds
  resources :users
  resources :relationships, only: [:show,:create, :destroy]
  
  root :to => 'home#index'
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match '/feed', to: 'home#feed'
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :post, :user_id
  belongs_to :user,:foreign_key => "user_id"
  validates :user_id, presence: true
  
  def user_from 
    self.user.name
  end 
  
  def attributes
    super.merge({'user_from' => user_from})
  end
  
  def self.all_friend_posts(user)
    user.relationships
  end
  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids
    where("user_id IN (?) OR user_id = ?", followed_user_ids, user)
  end
  
  def self.from_users_followers(user)
    followers = user.followers
    where("user_id IN (?) OR user_id = ?", followers, user)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :oauth_expires_at, :oauth_token, :provider, :status, :uid
  
  has_many :feeds, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  
  def following?(other_user)
    relationships.where(followed_id: other_user.id).exists?
    #find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.where(followed_id: other_user.id).first.delete
    #find_by(followed_id: other_user.id).destroy!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  helper_method :current_user, :signed_in

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  
  respond_to :json
  
  
  def index
    #@feeds = Feed.all
    #@feeds = Feed.find(:all, :conditions =>{ :user_id => current_user}) 
    @feeds = (Feed.from_users_followed_by(current_user) + Feed.from_users_followers(current_user)).uniq
    render :json => @feeds.to_json
    
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])
    #@feeds = Feed.from_users_followed_by(current_user)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    
    #Rails.logger.debug("Hello Server #{session.inspect} current user #{current_user.id}")
    
    
    @model = Feed.create(params[:feed].merge(:user_id => current_user.id))
    if @model.save
      render :json => @model.to_json
    else
      Rails.logger.debug("Hello Server #{@model.errors.full_messages}")
      render :json => { :errors => @model.errors.full_messages }
      
      
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :signed_in_user, only: [:feed]
  
  def feed
  end
  
  private    
    def signed_in_user
      redirect_to root_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  respond_to :json
  def show
    @is_followed = current_user.following?(@user = User.find(params[:id]))
    Rails.logger.debug("current user #{@is_followed}")
    render :json => { :is_followed => @is_followed.to_s}
    
  end
  
  def create
    #Rails.logger.debug("Hello Server #{session.inspect} current user #{params[:followed_id]}")
    @user = User.find(params[:followed_id])
    current_user.follow!(@user)
    render :json => @user.to_json
  end

  def destroy
    #@user = Relationship.find(params[:followed_id]).followed
    @user = User.find(params[:id])
    current_user.unfollow!(@user)
    render :json => @user.to_json
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to '/feed'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
  def oauth_failure
    #To handle the event the user authentication fails
    redirect_to root_url
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index]
  respond_to :json
  def index
    @user = User.find(:all, :conditions => ['id not in (?)', current_user]) 
    render :json => @user.to_json
  end
    
  def show
    @user = User.find(params[:id])
    #@user.is_following(current_user)
    #@user.merge({'is_following' => current_user.following?(@user)})
    #@user["test"] = current_user.following?(@user)
    render :json => @user.to_json(:include => [:feeds])
  end
  
  def update  
    Rails.logger.debug("Hello Server #{session.inspect} asdasd #{current_user}")
    render :json => @user.to_json(:include => :feeds)
  end
  
  private    
    def signed_in_user
      redirect_to root_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @feed.user_id %>
</p>

<p>
  <b>Post:</b>
  <%= @feed.post %>
</p>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/home/feed.html.erb
<div ng-app='usermsg' class='container' id='main'>
	
	<div id="AngularCtrl" ng-controller="UserListCtrl" class='row'>
		<div class='span3'>
			<div class='well sidebar-nav' id='users'>
				<ul class='nav nav-list' id='user-list'>
					<li class='nav-header'>
						Codebrahma Feed
					</li>
					<li class='active'>
						<a href='#users'> <i class='icon-inbox'></i> My Feed </a>
					</li>
					<li class='nav-header'>
						Users
						(
						<span id='num-users'>{{users.length}}</span>
						)
					</li>
				</ul>
				<ng:include src="'<%= asset_path("user-list.html") %>'"></ng:include>
				
			</div>
		</div>
		<div class='span9' id='messages'>
			<div ng-view></div>
		</div>
	</div>

	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Codebrahma</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= javascript_include_tag :defaults, "http://pdhar-faye-server.herokuapp.com/faye.js" %>
		<%= csrf_meta_tags %>
		<script type="text/javascript">
			if (window.location.hash == '#_=_') {
				window.location.hash = '';
			}
		</script>
		
	</head>
	<body>
		
		<div id="user_nav">
			<% if current_user %>
			Signed in as <strong><%= current_user.name %></strong>!
			<%= link_to "Sign out", signout_path, id: "sign_out" %>
			<% else %>
			<%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
			<% end %>
		</div>

		<%= yield %>

	</body>
</html>

app/views/users/index.html.erb
<h3>User Administration</h3>
<div class="span8">
<table class="table table-condensed">
	  <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          
          <th>Provider</th>
          <th></th>                                    
      </tr>
  </thead>   
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        
        <td><%= user.provider %></td>
        
    </tr>
  <% end %>
  </tbody>
</table>
</div>